### ISSUE TITLE
You may have to install mkfs.xfs

### ISSUE THREAD

**Issue by digitrux** [acantril/aws-sa-associate-saac02#7]
`$ sudo mkfs -t xfs /dev/xvdb`

`mkfs.xfs: No such file or directory`

So I had to run this command to install mkfs.xfs
`sudo yum install -y xfsprogs`

**Comment by acantril** [comment]
what lesson is this for? I dont recall using xfs for anything specifically ?

**Comment by digitrux** [comment]
Hi Adrian

This is SAA-C02.

Chapter: ELASTIC COMPUTE CLOUD (EC2) BASICS
[DEMO] EBS, Snapshots and Instance Store Volumes - PART1 Video @ 7:46

Thanks

**Comment by acantril** [comment]
did you pick amazon linux2 ? ive just run the demo and it works fine
it gets created with no issues.

**Comment by acantril** [comment]
ive googled the problem and amazon linux v1 doesnt come with xfs, v2 does.
